package template

const indexTemplate = `
<html>
  <head>
    <title>{{ user.name }} - いきものAZ エクスポート結果</title>
    <style>
      /* global layout */
      * {
        margin: 0;
        padding: 0;
      }
      body {
        background-color: #f7f7f7;
        color: #333333;
      }
      header {
        padding: 30px;
      }
      footer {
        padding: 1em 0;
      }
      h1 {
        text-align: center;
      }
      #container {
        margin: 0 auto;
        max-width: 900px;
      }
      main {
        padding: 40px;
        background-color: #ffffff;
        box-shadow: 2px 2px 4px 4px rgba(0,0,0,0.1);
      }

      section {
        margin: 2em 0;
      }
      h2 {
        margin-bottom: 0.5em;
      }
      ul {
        margin-left: 30px;
        list-style: none;
      }
      h3 {
        margin-top: 1em;
      }
      /*  layout */
      .meister::before {
        content: "🏅";
      }
      .tag {
        margin: 1px;
        padding: 1px 4px;
        border: solid 1px #afcdde;
        border-radius: 4px;
        background-color: #dff0f9;
        color: #1e4f6b;
      }
      .creature {
        padding: 1px 2px;
        color: #072b40;
      }
      .creature-place {
        font-size: 0.8em;
        color: #072b40;
      }
    </style>
  </head>
  <body>
    <div id="container">

      <header>
        <h1>いきものAZ エクスポート結果</h1>
      </header>
    
      <main>
        <section id="user">
          <h2>ユーザ情報</h2>
          <ul>
            <li>ユーザ名: {{ user.name }}</li>
            <li>プロフィール: {{ user.profile }}</li>
            <li>よく行く園館: {{ user.place }}</li>
            <li>
              マイスター:
                {{ #user.meister }}
                <span class="meister">{{.}}</span>
                {{ /user.meister }}
            </li>
          </ul>
        </section>

        <section id="article-list">
          <h2>投稿記事一覧</h2>
      
          <ul>
            {{ #articles }}
            <li>
              <article>
                <h3>{{ title }}</h3>
                <p class="created_at">{{ created_at }}</p>
                <p class="creatures">
                  {{ #creatures }}
                  <span class="creature">{{ name }}</span><span class="creature-place">@{{ place }}</span>
                  {{ /creatures }}
                </p>
                <p class="tags">
                  {{ #tags }}
                  <span class="tag">{{ . }}</span>
                  {{ /tags }}
                </p>
              </article>
            </li>
            {{ /articles }}
          </ul>
        </section>
      </main>

      <footer>
        Generated by <a href="https://github.com/t-sin/ikimonoaz-exporter">ikimonoaz-exporter</a>
      </footer>

    </div>
  </body>
</html>
`
