name: Build distributable zip file

on:
  push:
    tags:
      - 'v*'

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
    - name: Build binary
      run: go build -o ikimonoaz-exporter main.go
    - name: Pack files
      run: zip 'ikimonoaz-exporter-${{ matrix.target }}.zip' README.md LICENSE_J LICENSE_E ikimonoaz-exporter
    - name: Upload release files
      uses: softprops/action-gh-release@v1
      with:
        files: './*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update release page
      uses: softprops/action-gh-release@v1
      with:
        body_path: "RELEASENOTE.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.3
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit
        install: >-
          mingw-w64-i686-gcc
          zip
    - name: Build binary
      run: go build -o ikimonoaz-exporter.exe main.go
    - name: Pack files
      run: msys2 zip 'ikimonoaz-exporter-${{ matrix.target }}.zip' README.md LICENSE_J LICENSE_E ikimonoaz-exporter.exe
